// Builds code outputs from the DTCG token source (tokens/*.json).
//   dist/tokens.css   — :root (light) + html.dark (dark) CSS custom properties
//   dist/theme.css    — Tailwind v4 @theme bridge (--color-*, --spacing-*, …)
//   dist/tokens.ts    — token values as a typed JS object (for tooling/docs)
// Run: npm run build:tokens
import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';

const val = (t) => (t.value !== undefined ? t.value : t.$value);
const isColor = (t) => (t.$type || t.type) === 'color';

StyleDictionary.registerFormat({
  name: 'vadal/css-vars',
  format: ({ dictionary, options }) => {
    const filter = options.filter || (() => true);
    const lines = dictionary.allTokens
      .filter(filter)
      .map((t) => `  --${t.path.join('-')}: ${val(t)};`);
    return `${options.selector} {\n${lines.join('\n')}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'vadal/tw-theme',
  format: ({ dictionary }) => {
    const line = (t) => {
      const n = t.path.join('-');
      if (isColor(t)) return `  --color-${n}: var(--${n});`;
      if (n.startsWith('space-')) return `  --spacing-${n.slice(6)}: var(--${n});`;
      if (n.startsWith('radius-')) return `  --radius-${n.slice(7)}: var(--${n});`;
      if (n.startsWith('font-')) return `  --font-${n.slice(5)}: var(--${n});`;
      return null;
    };
    const lines = dictionary.allTokens.map(line).filter(Boolean);
    return `/* Tailwind v4 theme bridge — @import after tokens.css */\n@theme inline {\n${lines.join('\n')}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'vadal/ts',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((t) => `  "${t.path.join('-')}": ${JSON.stringify(val(t))}`);
    return `// GENERATED — token values (light mode). Prefer CSS vars at runtime; this is for tooling/docs.\nexport const tokens = {\n${entries.join(',\n')}\n} as const;\nexport type TokenName = keyof typeof tokens;\n`;
  },
});

const light = new StyleDictionary({
  source: ['tokens/semantic.light.json', 'tokens/component.json', 'tokens/base.json'],
  platforms: {
    css: {
      transforms: [],
      buildPath: 'dist/',
      files: [
        { destination: '_light.css', format: 'vadal/css-vars', options: { selector: ':root' } },
        { destination: '_light.scoped.css', format: 'vadal/css-vars', options: { selector: '[data-ds]' } },
        { destination: 'theme.css', format: 'vadal/tw-theme' },
        { destination: 'tokens.ts', format: 'vadal/ts' },
      ],
    },
  },
});
await light.buildAllPlatforms();

const dark = new StyleDictionary({
  source: ['tokens/semantic.dark.json', 'tokens/component.json'],
  platforms: {
    css: {
      transforms: [],
      buildPath: 'dist/',
      files: [
        { destination: '_dark.css', format: 'vadal/css-vars', options: { selector: 'html.dark', filter: isColor } },
        { destination: '_dark.scoped.css', format: 'vadal/css-vars', options: { selector: '.dark [data-ds]', filter: isColor } },
      ],
    },
  },
});
await dark.buildAllPlatforms();

const header =
  '/* GENERATED by @vadal/design-system from tokens/*.json — DO NOT EDIT BY HAND.\n' +
  '   Edit tokens/*.json, then: `npm run build:tokens` (and `npm run figma:push` to sync Figma). */\n\n';
const l = await fs.readFile('dist/_light.css', 'utf8');
const d = await fs.readFile('dist/_dark.css', 'utf8');
await fs.writeFile('dist/tokens.css', header + l + '\n' + d);
const ls = await fs.readFile('dist/_light.scoped.css', 'utf8');
const ds = await fs.readFile('dist/_dark.scoped.css', 'utf8');
await fs.writeFile('dist/tokens.scoped.css', header + ls + '\n' + ds);
await fs.rm('dist/_light.css');
await fs.rm('dist/_dark.css');
await fs.rm('dist/_light.scoped.css');
await fs.rm('dist/_dark.scoped.css');
console.log('✓ wrote dist/tokens.css, dist/tokens.scoped.css, dist/theme.css, dist/tokens.ts');
