/**
 * Provider resolution — the single switch between demo and real AI.
 *
 * Set ANTHROPIC_API_KEY and the product starts using the model. Nothing else
 * changes: same chunk stream, same citations, same tool-confirmation flow, same
 * UI. That is the whole reason the runtime was built before the key arrived.
 */
import { mockProvider } from "./mock";
import { anthropicProvider } from "./anthropic";
import type { AiProvider } from "./types";

export function getProvider(): AiProvider {
  return anthropicProvider.available ? anthropicProvider : mockProvider;
}

/** Surfaced in Settings so it is never a mystery which one answered. */
export function providerStatus() {
  const live = anthropicProvider.available;
  return {
    name: live ? "anthropic" : "mock",
    live,
    label: live ? "Live model" : "Demo responses",
    detail: live
      ? "Answers are generated by Claude, grounded in your workspace's documents."
      : "No API key configured — answers come from your workspace's documents and scripted language. Retrieval, citations, confirmation and undo are real.",
  };
}

export * from "./types";
